(let ((files-to-compile '(("lib.lisp" . "lib.compiled")
                          ("batch-compile.lisp" . "batch-compile.compiled")
                          ("repl.lisp" . "repl.compiled")
			  ("compiler.lisp" . "compiler.compiled")
			  ("vmboot.lisp" . "vmboot.compiled")
                          ("eval.lisp" . "eval.compiled")
                          ("load.lisp" . "load.compiled")
                          ("raise.lisp" . "raise.compiled")
			  ("bootstrap.lisp" . "bootstrap.compiled"))))
  (tagbody
   next-file
     (if (eq files-to-compile nil)
	 (go done))
     (let ((file (car files-to-compile)))
       (print file)
       (let ((source-file (car file))
	     (compiled-file (cdr file)))
	 (let ((in-stream (open source-file :read))
	       (out-stream (open compiled-file :write)))
	   (condition-case eof
	       (let (input)
		 (tagbody
		  loop
		    (setq input (read1 in-stream))
		    (write (compile4-toplevel input) out-stream)
		    (go loop)))
	     (end-of-file nil)))))
     (setq files-to-compile (cdr files-to-compile))
     (go next-file)
   done))
