;; not used
(defun list-to-vector (list)
  (let ((length (length list)))
    (let ((vector (make-vector length))
	  (i 0))
      (dolist (obj list)
	(set-svref vector i obj)
	(setq i (+ 1 i)))
      vector)))

(defun build-label-alist (list)
  (let ((i 0)
	(label-alist nil))
    (dolist (obj list)
      (if (and (consp obj) (eq (car obj) 'label))
	  (let ((label (cadr obj)))
	    (when (not (null (assoc label label-alist)))
	      (raise 'duplicate-label))
	    (setq label-alist (cons (cons label i) label-alist)))
	  (setq i (+ 1 i))))
    (cons label-alist i)))

(defparameter +jump-instructions+ '(jmp jmp-if-nil))

(defun assemble (list)
  (let ((label-info (build-label-alist list)))
    (let ((label-alist (car label-info))
	  (length (cdr label-info)))
      (let ((vector (make-vector length))
	    (i 0)
	    (state nil))
	(dolist (obj list)
	  (when (not (consp obj))
	    (if state
		(progn
		  (setq state nil)
		  (set-svref vector i (cdr (assoc obj label-alist))))
		(progn
		  (setq state (find obj +jump-instructions+))
		  (set-svref vector i obj)))
	    (setq i (+ 1 i))))
	vector))))

(defun lexical-context-block-alist (ctxt)
  (svref ctxt 0))

(defun lexical-context-next-block-number (ctxt)
  (svref ctxt 1))

(defun lexical-context-bindings (ctxt)
  (svref ctxt 2))

(defun lexical-context-binding-count (ctxt)
  (svref ctxt 3))

(defun lexical-context-set-block-alist (ctxt block-alist)
  (set-svref ctxt 0 block-alist))

(defun lexical-context-set-next-block-number (ctxt next-block-number)
  (set-svref ctxt 1 next-block-number))

(defun lexical-context-set-bindings (ctxt bindings)
  (set-svref ctxt 2 bindings))

(defun lexical-context-set-binding-count (ctxt count)
  (set-svref ctxt 3 count))

(defun make-lexical-context ()
  (let ((ctxt (make-vector 4)))
    (lexical-context-set-block-alist ctxt nil)
    (lexical-context-set-next-block-number ctxt 0)
    (lexical-context-set-bindings ctxt nil)
    (lexical-context-set-binding-count ctxt 0)
    ctxt))

(defun lexical-context-enter-scope (ctxt bindings)
  (lexical-context-set-bindings ctxt (cons bindings (lexical-context-bindings ctxt)))
  (lexical-context-set-binding-count ctxt (+ (lexical-context-binding-count ctxt) (length bindings))))

(defun lexical-context-leave-scope (ctxt)
  (let ((bindings (lexical-context-bindings ctxt)))
    (lexical-context-set-binding-count ctxt (- (lexical-context-binding-count ctxt) (length (car bindings))))
    (lexical-context-set-bindings ctxt (cdr (lexical-context-bindings ctxt)))))

(defun lexical-context-lookup (ctxt symbol)
  (let ((bindings (lexical-context-bindings ctxt))
	(i (lexical-context-binding-count ctxt)))
    (while (not (null bindings))
      (let ((bindings-one-scope (car bindings)))
	(while (not (null bindings-one-scope))
	  (when (eq (car bindings-one-scope) symbol)
	    (return-from lexical-context-lookup i))
	  (setq i (- i 1))
	  (setq bindings-one-scope (cdr bindings-one-scope))))
      (setq bindings (cdr bindings))))
  nil)

(defun convert-quasiquote1 (expr)
  (cond ((symbolp expr) `(quote ,expr))
	((integerp expr) expr)
	((consp expr)
	 (cond ((and (symbolp (car expr)) (eq (car expr) 'unquote))
		(convert-quasiquote (cadr expr)))
	       ((and (consp (cdr expr)) (consp (cadr expr))
		     (eq (caadr expr) 'unquote-splice))
		`(cons ,(convert-quasiquote1 (car expr))
		       ,(cadr (cadr expr))))
	       (t 
		`(cons ,(convert-quasiquote1 (car expr))
		       ,(convert-quasiquote1 (cdr expr))))))
	(t (raise 'unhandled-quasiquote-case expr))))

(defun convert-quasiquote (expr)
  (cond ((and (consp expr) (eq (car expr) 'quasiquote))
	 (convert-quasiquote1 (cadr expr)))
	((consp expr)
	 (cons (convert-quasiquote (car expr))
	       (convert-quasiquote (cdr expr))))
	((vectorp expr)
	 (let ((result (make-vector (length expr))))
	   (dotimes (i (length expr))
	     (set-svref result i (convert-quasiquote (svref expr i))))
	   result))
	(t expr)))

(defun compile4-list (forms ctxt)
  (if (null forms)
      nil
      (append (compile4 (car forms) ctxt) (compile4-list (cdr forms) ctxt))))
  
;; XXX not sure this is right as each expression will leave a value on
;; the stack.  Probably need to stick a pop between each form
(defun compile4-progn (expr ctxt)
  (assert (eq (car expr) 'progn))
  (compile4-list (cdr expr) ctxt))

;; This should check the arg count somehow
(defun compile4-lambda (expr ctxt)
  (assert (eq (car expr) 'lambda))
  (let ((arglist (cadr expr))
	(body (cddr expr)))
    (let ((effective-arglist (append arglist (cons '%provided-arg-count nil))))
      (lexical-context-enter-scope ctxt effective-arglist)
      (let ((compiled-body (compile4 `(progn ,@body) ctxt)))
	(lexical-context-leave-scope ctxt)
	(let ((len (length compiled-body))
	      (code (assemble compiled-body)))
	  (let ((result `(push ,code push 1 push %vm-make-function call)))
	    result))))))

(defun compile4-if (expr ctxt)
  (assert (eq (car expr) 'if))
  (let ((test-form (cadr expr))
	(then-form (car (cddr expr)))
	(else-form (cadr (cddr expr))))
    (let ((label1 (gensym))
	  (label2 (gensym)))
      `(,@(compile4 test-form ctxt)
      	  jmp-if-nil ,label1
	  ,@(compile4 then-form ctxt)
	  jmp ,label2
	  (label ,label1)
	  ,@(compile4 else-form ctxt)
	  (label ,label2)))))

;; This is problematic as the lexical scope stuff depends on the frame
;; pointer which doesn't work here as we have no function call
(defun compile4-let (expr ctxt)
  (assert (eq (car expr) 'let))
  (let ((bindings (cadr expr))
	(body (caddr expr)))
    (let ((arglist (mapcar #'car bindings))
	  (forms (mapcar #'cadr bindings))
	  (n (length bindings)))
      (let ((result (compile4-list forms ctxt)))
	(lexical-context-enter-scope ctxt arglist)
	(prog1
	    (append (append result (compile4-progn `(progn ,body) ctxt)) `(swap-pop ,n))
	  (lexical-context-leave-scope ctxt))))))

(defun compile4 (expr ctxt)
  (cond ((atom expr) 
	 (if (or (stringp expr) (integerp expr) (eq t expr) (eq nil expr))
	     `(push ,expr)
	     `(copy2 ,(lexical-context-lookup ctxt expr))))
	((symbolp (car expr))
	 (let ((sym (car expr)))
	   (cond ((eq sym 'function)
		  (let ((function (cadr expr)))
		    (if (symbolp function)
			`(push ,function)
			(compile4-lambda function ctxt))))
		 ((eq sym 'progn)
		  (compile4-progn expr ctxt))
		 ((eq sym 'quote)
		  `(push ,(cadr expr)))
		 ((eq sym 'if)
		  (compile4-if expr ctxt))
		 ((eq sym 'let)
		  (compile4-let expr ctxt))
		 (t (let ((arg-count 0)
			  (result nil))
		      (dolist (arg (cdr expr))
			(setq result (append result (compile4 arg ctxt)))
			(setq arg-count (+ 1 arg-count)))
		      (let ((pass-arg-count `(push ,arg-count))
			    (more-stuff `(push ,sym call)))
			(setq result (append (append result pass-arg-count) more-stuff))
			result))))))
	(t (raise 'bad-expression))))
      
;; Ultimately this should simply be called `compile`
(defun compile4-toplevel (expr)
  (let ((ctxt (make-lexical-context)))
    (assemble (compile4 (convert-quasiquote expr) ctxt))))
